### ISSUE TITLE
cannot connect with Jlink v5.10+

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_Adalink#16]
failed when connect with jlink version 5.10
Segger release note https://www.segger.com/j-link-release-notes.html say
 - **J-Link Commander: Commander does not perform a auto-connect with search on all interfaces any longer, by default.**

It could be a hint or not.

```
adalink -v stm32f2 --programmer jlink -i
INFO:adalink.programmers.jlink:Using path to JLinkExe: JLink.exe
INFO:adalink.programmers.jlink:Using parameters to JLinkExe: -device STM32F205RG -if swd -speed auto
DEBUG:adalink.programmers.jlink:Using script file name: c:\users\hathach\appdata\local\temp\tmpijwu80
DEBUG:adalink.programmers.jlink:Running JLink commands: q
DEBUG:adalink.programmers.jlink:JLink response: SEGGER J-Link Commander V5.10m (Compiled Feb 15 2016 18:48:35)
DLL version V5.10m, compiled Feb 15 2016 18:47:57


Script file read successfully.
Processing script file...


Script processing completed.


Traceback (most recent call last):
  File "C:\Python27\Scripts\adalink-script.py", line 9, in <module>
    load_entry_point('adalink==2.0.0', 'console_scripts', 'adalink')()
  File "C:\Python27\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "c:\users\hathach\dropbox\adafruit\workspace\adafruit_adalink\adalink\core.py", line 81, in _callback
    raise AdaLinkError('Could not find {0}, is it connected?'.format(self.name))
adalink.errors.AdaLinkError: Could not find stm32f2, is it connected?
```

**Comment by microbuilder** [comment]
This should be fixed with this commit ... perhaps try updating to the latest AdaLink source? https://github.com/adafruit/Adafruit_Adalink/commit/ece8746962d4f75e24000c2d9430c545a05f8830
